name: Hello wor
on:
  pull_request:
    types: [opened]
jobs:
  startup:
    name: Startup job
    runs-on: ubuntu-latest
    steps:
     - run: echo "hello world"

  build:
    name: here is my build job
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs: startup
    steps:
      - name: 'Comment on PR'
        run: gh pr comment $PR_URL --body "Thanks for the pull request, we will review it shortly"
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PR_URL: ${{ github.event.pull_request.html_url }}

      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Check for buttons trigger'
        run: ./.github/scripts/checker.sh
        env:
          FILE: ./src/components/Button.js







